### ISSUE TITLE
Webpack build breaks with latest release

### ISSUE THREAD

**Issue by bodymovin** [philbooth/check-types.js#74]
We're getting an error after building our bundle with webpack:
Cannot set property 'of' of undefined
this function minified breaks:
```
function createOfPredicates (key) {
    predicates[key].of = createModifiedFunctions(
      [ ofModifier.bind(null, null), predicates[key], predicates, null ]
    );
  }
```

after logging we found it doesn't find the key 'array'

when not compiled, everything works fine.
rolling back to version 7.0.1 fixes it.

**Comment by philbooth** [comment]
Mea culpa!

I updated the minifier dependency and failed to test the minified output, sorry. But I just published `7.1.1`, which should fix it for you. Let me know how it goes!

**Comment by bodymovin** [comment]
Unfortunately it didn't solve our problem because we are compiling the library from the unminified version.
But it helped us to find out what was the issue.
We also had to change our webpack config to set mangle to false.
thanks for the quick help!

**Comment by philbooth** [comment]
Hmmm, interesting. Going to see if I can mess with the code a bit to make the name mangling work sanely.

**Comment by philbooth** [comment]
@bodymovin, I've reverted the change I made that broke name-mangling and published a new release. If you build with version `7.1.2`, you should be able to revert your webpack config to what it was previously.

**Comment by bodymovin** [comment]
working, thanks.
